# force run: 41
language: python
python:
  - "2.7"
before_install:
  - sh -x ./install_depends/opensips.sh
script:
    sh -x ./test_run.sh
env:
#
  - MM_TYPE=opensips MM_BRANCH=2.3 MM_REV=03b4a7eae52f21b0676d0ac1a337e6a996c2de42 RTPP_BRANCH=master RTPPC_TYPE=udp
  - MM_TYPE=opensips MM_BRANCH=2.3 MM_REV=9667332c36bfa5e7b10a42524a4d2153e3f710bb RTPP_BRANCH=master RTPPC_TYPE=udp6
  - MM_TYPE=opensips MM_BRANCH=2.3 RTPP_BRANCH=master RTPPC_TYPE=unix
