# force run: 41
language: python
python:
  - "2.7"
before_install:
  - sh -x ./install_depends/opensips.sh
script:
    sh -x ./test_run.sh
env:
#
  - MM_TYPE=opensips MM_BRANCH=2.3 MM_REV=03b4a7eae52f21b0676d0ac1a337e6a996c2de42 RTPP_BRANCH=master RTPPC_TYPE=unix
  - MM_TYPE=opensips MM_BRANCH=2.3 MM_REV=90ac8b6430025ecbab22784afa457fa8ad374439 RTPP_BRANCH=master RTPPC_TYPE=unix
  - MM_TYPE=opensips MM_BRANCH=2.3 MM_REV=7cdd3ee99d6c46dcde238c8571f21c46e85e82b3 RTPP_BRANCH=master RTPPC_TYPE=unix
  - MM_TYPE=opensips MM_BRANCH=2.3 MM_REV=ae34313cd86379e4322d37dd901b710746974303 RTPP_BRANCH=master RTPPC_TYPE=unix
  - MM_TYPE=opensips MM_BRANCH=2.3 MM_REV=752e69fbb651355db50d3fed26e3cc733ac0b51d RTPP_BRANCH=master RTPPC_TYPE=unix
  - MM_TYPE=opensips MM_BRANCH=2.3 MM_REV=098ddfb129a035749241e73e4a2b608963ce46a9 RTPP_BRANCH=master RTPPC_TYPE=unix
  - MM_TYPE=opensips MM_BRANCH=2.3 MM_REV=bc5b713cebc7c0d67c6bb3ca5673c9fb25e641dc RTPP_BRANCH=master RTPPC_TYPE=unix
  - MM_TYPE=opensips MM_BRANCH=2.3 MM_REV=5ff51e8599d4ad3ec0ee6fff4eb1eaef1578564a RTPP_BRANCH=master RTPPC_TYPE=unix
  - MM_TYPE=opensips MM_BRANCH=2.3 MM_REV=e5d23c7acdf43ff5c83bbd78d0e33c475f8be009 RTPP_BRANCH=master RTPPC_TYPE=unix
  - MM_TYPE=opensips MM_BRANCH=2.3 MM_REV=f27344a860d03dbbb9e9dd921586d051abac9daf RTPP_BRANCH=master RTPPC_TYPE=unix
  - MM_TYPE=opensips MM_BRANCH=2.3 MM_REV=211ce1d4ef1e9fd223a44ab235960101025720e3 RTPP_BRANCH=master RTPPC_TYPE=unix
  - MM_TYPE=opensips MM_BRANCH=2.3 MM_REV=9fc71ace82bee6f03572cf1eb03df7b3d3612979 RTPP_BRANCH=master RTPPC_TYPE=unix
  - MM_TYPE=opensips MM_BRANCH=2.3 MM_REV=853f4c6e962ed88dfbe9a794d7086f6f87c398e6 RTPP_BRANCH=master RTPPC_TYPE=unix
  - MM_TYPE=opensips MM_BRANCH=2.3 MM_REV=aecb7e6f71f6913cac63abbce31e83b2131787c1 RTPP_BRANCH=master RTPPC_TYPE=unix
  - MM_TYPE=opensips MM_BRANCH=2.3 MM_REV=7595d76f124b3303fbd10cc6b5adc93ea405f6aa RTPP_BRANCH=master RTPPC_TYPE=unix
  - MM_TYPE=opensips MM_BRANCH=2.3 MM_REV=f2f805157204365637759fc774478237e6ae8ed8 RTPP_BRANCH=master RTPPC_TYPE=unix
  - MM_TYPE=opensips MM_BRANCH=2.3 MM_REV=36c698d3a155d9a8c89e4fd5015f6c3f8f5e0be0 RTPP_BRANCH=master RTPPC_TYPE=unix
  - MM_TYPE=opensips MM_BRANCH=2.3 MM_REV=43ef62441292b7f6b4435313b5ccc7d76274ef3a RTPP_BRANCH=master RTPPC_TYPE=unix
  - MM_TYPE=opensips MM_BRANCH=2.3 MM_REV=df6a9a9bc3f7c65165639a9c88a4359698d0e5b8 RTPP_BRANCH=master RTPPC_TYPE=unix
  - MM_TYPE=opensips MM_BRANCH=2.3 MM_REV=302a365420505f40df37b7a5cf521ee8c3d04d7f RTPP_BRANCH=master RTPPC_TYPE=unix
  - MM_TYPE=opensips MM_BRANCH=2.3 MM_REV=4e9d3663ab1db6a63a8a21b12505bde7e913de81 RTPP_BRANCH=master RTPPC_TYPE=unix
  - MM_TYPE=opensips MM_BRANCH=2.3 MM_REV=f36189716bb02ffba07877038ce2bc79701e8432 RTPP_BRANCH=master RTPPC_TYPE=unix
  - MM_TYPE=opensips MM_BRANCH=2.3 MM_REV=5b809b1820d28768ea985d8779ec176ca24d281a RTPP_BRANCH=master RTPPC_TYPE=unix
  - MM_TYPE=opensips MM_BRANCH=2.3 MM_REV=6bb48d0a90840f099a68b788191101fccbbcf05b RTPP_BRANCH=master RTPPC_TYPE=unix
  - MM_TYPE=opensips MM_BRANCH=2.3 MM_REV=d38a9b1db8df8399a296d978b4a8211066713cb2 RTPP_BRANCH=master RTPPC_TYPE=unix
  - MM_TYPE=opensips MM_BRANCH=2.3 MM_REV=a8f20907b122b1bff0ac21bf751683daef3e31ca RTPP_BRANCH=master RTPPC_TYPE=unix
  - MM_TYPE=opensips MM_BRANCH=2.3 MM_REV=5022725c47a1e3857ee83fd0563199b06a40b21a RTPP_BRANCH=master RTPPC_TYPE=unix
  - MM_TYPE=opensips MM_BRANCH=2.3 MM_REV=4975a9fab79b5e12bbc8c64d9ccbef798618da23 RTPP_BRANCH=master RTPPC_TYPE=unix
  - MM_TYPE=opensips MM_BRANCH=2.3 MM_REV=43764b66adec9b6c4468c368fb584a7637b4bbf9 RTPP_BRANCH=master RTPPC_TYPE=unix
  - MM_TYPE=opensips MM_BRANCH=2.3 MM_REV=1d9b6cd6b77899e07d8d46e60c3dfae4c0b26682 RTPP_BRANCH=master RTPPC_TYPE=unix
  - MM_TYPE=opensips MM_BRANCH=2.3 MM_REV=b33c84392e4bd2383c28ffc170efd4cea50fae1c RTPP_BRANCH=master RTPPC_TYPE=unix
  - MM_TYPE=opensips MM_BRANCH=2.3 MM_REV=9667332c36bfa5e7b10a42524a4d2153e3f710bb RTPP_BRANCH=master RTPPC_TYPE=unix
