# force run: 41
language: python
python:
  - "2.7"
before_install:
  - sh -x ./install_depends/opensips.sh
script:
    sh -x ./test_run.sh
env:
#
  - MM_TYPE=opensips MM_BRANCH=2.3 MM_REV=302a365420505f40df37b7a5cf521ee8c3d04d7f RTPP_BRANCH=master RTPPC_TYPE=unix
  - MM_TYPE=opensips MM_BRANCH=2.3 MM_REV=8ba4e99484479cd0724b57d9fe83bae479cdc062 RTPP_BRANCH=master RTPPC_TYPE=unix
  - MM_TYPE=opensips MM_BRANCH=2.3 MM_REV=db49bb5bb516601ff213db7096d3abc281d07df4 RTPP_BRANCH=master RTPPC_TYPE=unix
  - MM_TYPE=opensips MM_BRANCH=2.3 MM_REV=493656792ed327751f8d909b418d742f1dc53942 RTPP_BRANCH=master RTPPC_TYPE=unix
  - MM_TYPE=opensips MM_BRANCH=2.3 MM_REV=1bb0e9dd88e2eb702c44b31a842f1004feb97dea RTPP_BRANCH=master RTPPC_TYPE=unix
  - MM_TYPE=opensips MM_BRANCH=2.3 MM_REV=95e2191dad8390c76b41377e33fcdcd0923816ca RTPP_BRANCH=master RTPPC_TYPE=unix
  - MM_TYPE=opensips MM_BRANCH=2.3 MM_REV=d954818905ecf3a186a131888fa6738390d5f8be RTPP_BRANCH=master RTPPC_TYPE=unix
  - MM_TYPE=opensips MM_BRANCH=2.3 MM_REV=544fb24ecb4550a033e318259bd8f9953635e9e1 RTPP_BRANCH=master RTPPC_TYPE=unix
  - MM_TYPE=opensips MM_BRANCH=2.3 MM_REV=519862c84c170d8dfbf3fc49eb8b1b08ca3638f0 RTPP_BRANCH=master RTPPC_TYPE=unix
  - MM_TYPE=opensips MM_BRANCH=2.3 MM_REV=85ed33e7affb866b1d9e3c3709f53a74f5cdab78 RTPP_BRANCH=master RTPPC_TYPE=unix
  - MM_TYPE=opensips MM_BRANCH=2.3 MM_REV=9e4a8976a9b35b40a7335fc686e19f500bd61cfd RTPP_BRANCH=master RTPPC_TYPE=unix
  - MM_TYPE=opensips MM_BRANCH=2.3 MM_REV=297df1e8c5464e1a1f32a5b5cb6c1d7d37910e14 RTPP_BRANCH=master RTPPC_TYPE=unix
  - MM_TYPE=opensips MM_BRANCH=2.3 MM_REV=c49d9d3bc52b2075f96f745ef0d85537f03f87df RTPP_BRANCH=master RTPPC_TYPE=unix
  - MM_TYPE=opensips MM_BRANCH=2.3 MM_REV=3a987d3b122ef8c9da00433632474372c917acaf RTPP_BRANCH=master RTPPC_TYPE=unix
  - MM_TYPE=opensips MM_BRANCH=2.3 MM_REV=a49a76209681c8bd34b57862f8be0207b3f3a114 RTPP_BRANCH=master RTPPC_TYPE=unix
  - MM_TYPE=opensips MM_BRANCH=2.3 MM_REV=7acaf63443604fc4d01a846761677892e3dc78a2 RTPP_BRANCH=master RTPPC_TYPE=unix
  - MM_TYPE=opensips MM_BRANCH=2.3 MM_REV=bcaa5324baa188bc1547e107f10a3c4b3e7de8d2 RTPP_BRANCH=master RTPPC_TYPE=unix
  - MM_TYPE=opensips MM_BRANCH=2.3 MM_REV=51c23aaf0b62893c01f458eea3dc65d7098ce526 RTPP_BRANCH=master RTPPC_TYPE=unix
  - MM_TYPE=opensips MM_BRANCH=2.3 MM_REV=d568d2116d2f9ba6e0b360a42cdbfde497e47736 RTPP_BRANCH=master RTPPC_TYPE=unix
  - MM_TYPE=opensips MM_BRANCH=2.3 MM_REV=a46124fac25c36c0d7d1e0a832e3f59c164845fb RTPP_BRANCH=master RTPPC_TYPE=unix
  - MM_TYPE=opensips MM_BRANCH=2.3 MM_REV=a4adc86ae2d5acad0ba79edf3b363ec22b4888ae RTPP_BRANCH=master RTPPC_TYPE=unix
  - MM_TYPE=opensips MM_BRANCH=2.3 MM_REV=2411deafceb1cc5be2e7a0aea3cae0c05e78d090 RTPP_BRANCH=master RTPPC_TYPE=unix
  - MM_TYPE=opensips MM_BRANCH=2.3 MM_REV=6ba33b589eefeca2fe6e4e8503c56e4f34d33abd RTPP_BRANCH=master RTPPC_TYPE=unix
  - MM_TYPE=opensips MM_BRANCH=2.3 MM_REV=42c6820349274398430d0c42dc1cad7d39a59a73 RTPP_BRANCH=master RTPPC_TYPE=unix
  - MM_TYPE=opensips MM_BRANCH=2.3 MM_REV=9bba5954cb86bc56f81887087f0dc4ff20923e74 RTPP_BRANCH=master RTPPC_TYPE=unix
  - MM_TYPE=opensips MM_BRANCH=2.3 MM_REV=5ecf882c65b66bae762d1b436e9329f7b29864a3 RTPP_BRANCH=master RTPPC_TYPE=unix
  - MM_TYPE=opensips MM_BRANCH=2.3 MM_REV=33d43262da179f3fe559edb04880537ef3c31a91 RTPP_BRANCH=master RTPPC_TYPE=unix
  - MM_TYPE=opensips MM_BRANCH=2.3 MM_REV=05e6a0abf9a9a80edbf6ff775bb37e4be1672dc9 RTPP_BRANCH=master RTPPC_TYPE=unix
  - MM_TYPE=opensips MM_BRANCH=2.3 MM_REV=d4f99f78640e4eb84d70ff7737d7ed9739ad5172 RTPP_BRANCH=master RTPPC_TYPE=unix
  - MM_TYPE=opensips MM_BRANCH=2.3 MM_REV=4ba179df58516bba455248bc1d26f86e49ef82e5 RTPP_BRANCH=master RTPPC_TYPE=unix
  - MM_TYPE=opensips MM_BRANCH=2.3 MM_REV=fc4793e39c1ab9cbb92868657d7492fcb14771de RTPP_BRANCH=master RTPPC_TYPE=unix
  - MM_TYPE=opensips MM_BRANCH=2.3 MM_REV=9667332c36bfa5e7b10a42524a4d2153e3f710bb RTPP_BRANCH=master RTPPC_TYPE=unix
